### ISSUE TITLE
Module name conflict

### ISSUE THREAD

**Issue by Foxboron** [palantir/python-jsonrpc-server#10]
This project uses the same module name `jsonrpc` as another older project. This causes conflicts when packaging it up for distributions, and possibly with pip. I recommend changing the module name to `jsonrpc-server` if possible.

https://github.com/pavlov99/json-rpc
https://github.com/palantir/python-jsonrpc-server

**Comment by pavlov99** [comment]
Dear Palantir team @palantirtech and @gatesn 

I would like to follow up on @Foxboron message and initiate a discussion about module name conflicts. I'm maintaining `json-rpc` package which is installed as `jsonrpc`. Current `python-jsonrpc-server` uses the same package name in virtual environment, moreover, we used the same file `jsonrpc/exceptions.py` and pip keeps only one version of it. This raises the following error:

```
> pip install python-language-server[all]
> pip install json-rpc
> pyls --help
Traceback (most recent call last):
  File "venv/bin/pyls", line 11, in <module>
    load_entry_point('python-language-server==0.21.4', 'console_scripts', 'pyls')()
  File "/tmp/jsonrpc-bug/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/jsonrpc-bug/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/tmp/jsonrpc-bug/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/tmp/jsonrpc-bug/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/jsonrpc-bug/venv/lib/python3.6/site-packages/pyls/__main__.py", line 7, in <module>
    from .python_ls import start_io_lang_server, start_tcp_lang_server, PythonLanguageServer
  File "/tmp/jsonrpc-bug/venv/lib/python3.6/site-packages/pyls/python_ls.py", line 7, in <module>
    from jsonrpc.endpoint import Endpoint
  File "/tmp/jsonrpc-bug/venv/lib/python3.6/site-packages/jsonrpc/endpoint.py", line 7, in <module>
    from .exceptions import JsonRpcException, JsonRpcRequestCancelled, JsonRpcInternalError, JsonRpcMethodNotFound
ImportError: cannot import name 'JsonRpcException'
```

Another related issue has been raised in json-rpc project: https://github.com/pavlov99/json-rpc/issues/103

In order to solve this we would likely need one party to rename the package name. Would you be kind to use another name, e.g. `jsonrpc-server` as @Foxboron suggested, for the package? json-rpc was in the ecosystem since 2013 and is used by [almost 400 other projects](https://github.com/pavlov99/json-rpc/network/dependents) now.

Please let me know your ideas about how we could resolve the issue.

Cheers,
Kirill

**Comment by gatesn** [comment]
I will take a look at renaming this

**Comment by CarlQLange** [comment]
Wow, this was a confusing issue to debug! 

In Spacemacs, you can use the anaconda or LSP backends for python [link](
https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/python#anaconda). Anaconda uses json-rpc (the one by @pavlov99), and the LSP backend uses this one. So if you want to switch between the two, you get this issue. :)
