### ISSUE TITLE
Compatibility with ujson 2.x?

### ISSUE THREAD

**Issue by hosiet** [palantir/python-jsonrpc-server#36]
This project is using ujson but the version is limited to ujson <= 1.35. The ujson upstream has made 2.x releases: https://github.com/ultrajson/ultrajson/releases

Any possibility to test compatibility with new library and relax version requirement? Thanks!

**Comment by frenzymadness** [comment]
:+1: 
We'd like to package this SW to Fedora Linux but all our supported versions have ujson 2.0.0 (even EPEL 8). We are running the tests and it seems that all of them are passing with ujson 2 (except the disabled tests mentioned in #33).

**Comment by bnavigator** [comment]
OpenSUSE has unpinned ujson for python-jsonrpc-server and python-language-server as well.
https://build.opensuse.org/package/show/openSUSE:Factory/python-python-jsonrpc-server
https://build.opensuse.org/package/show/openSUSE:Factory/python-python-language-server

Dear fellow distro maintainers: The maintainers of python-jsonrpc-server and python-language-server really like to pin stuff  to specific versions and any attempt to talk them out of it is not very appreciated. Good luck with packaging and please continue to report the results of your attempts in the upstream trackers so that other distro maintainers can benefit from it.
https://github.com/palantir/python-language-server/issues/744

**Comment by elMor3no** [comment]
Also in Debian we have the same problem. 
With ujson 4.0.1 is not working any more

**Comment by ccordoba12** [comment]
Our latest version (0.4.0) is compatible with ujson >=3.0:

https://github.com/palantir/python-jsonrpc-server/blob/222e0d5ba34645d0f19dc6e85d7556f2dfc423e3/setup.py#L14_L17

So this no longer applies.

**Comment by elMor3no** [comment]
Unfortunately in all my attempts to package for Debian I get error when I run the tests 

Here are more information https://github.com/palantir/python-jsonrpc-server/issues/43#issuecomment-722721156

**Comment by ccordoba12** [comment]
Sorry but I can't help you with issues in specific distros. We test on Ubuntu and our tests pass just fine.
